# Generated by Django 4.0.2 on 2022-02-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('tagname', models.CharField(max_length=100)),
                ('fontcolor', models.CharField(max_length=50)),
                ('bgcolor', models.CharField(max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('planDate', models.DateField()),
                ('endDate', models.DateField()),
                ('endYn', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Calc',
        ),
    ]
