# Generated by Django 4.0.2 on 2022-02-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0005_alter_todo_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='detail',
        ),
    ]
